<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $contract->title }} - Export</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; line-height: 1.6; color: #333; margin: 0; padding: 20px; }
        .header { border-bottom: 2px solid #1E3A8A; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; color: #1E3A8A; margin: 0 0 10px 0; }
        .meta-data { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .meta-data th { text-align: left; padding: 8px; background-color: #F3F4F6; width: 40%; font-weight: bold; }
        .meta-data td { padding: 8px; border-bottom: 1px solid #E5E7EB; }
        .section-title { font-size: 18px; font-weight: bold; color: #1E3A8A; margin-top: 30px; margin-bottom: 15px; border-bottom: 1px solid #1E3A8A; padding-bottom: 5px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th, .table td { border: 1px solid #E5E7EB; padding: 8px; text-align: left; }
        .table th { background-color: #F3F4F6; }
        .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #6B7280; border-top: 1px solid #E5E7EB; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{ $contract->title }}</h1>
        <p style="margin: 0; color: #6B7280;">Reference Number: <strong>{{ $contract->reference_number }}</strong></p>
    </div>

    <table class="meta-data">
        <tr><th>Vendor Name</th><td>{{ $contract->vendor_name }}</td></tr>
        <tr><th>Contract Status</th><td style="text-transform: capitalize;">{{ $contract->status }}</td></tr>
        <tr><th>Priority Level</th><td style="text-transform: capitalize;">{{ $contract->priority }}</td></tr>
        <tr><th>Total Value</th><td>${{ number_format($contract->contract_value, 2) }}</td></tr>
        <tr><th>Start Date</th><td>{{ $contract->start_date }}</td></tr>
        <tr><th>End Date</th><td>{{ $contract->end_date }}</td></tr>
        <tr><th>Generated By</th><td>{{ Auth::user()->name ?? 'System' }} on {{ now()->format('Y-m-d H:i') }}</td></tr>
    </table>

    <div class="section-title">Contract Description</div>
    <p>{{ $contract->description ?? 'No detailed description provided.' }}</p>

    @if($contract->parties && count($contract->parties) > 0)
    <div class="section-title">Involved Parties</div>
    <table class="table">
        <tr><th>Party Name</th><th>Role Type</th></tr>
        @foreach($contract->parties as $party)
        <tr>
            <td>{{ $party['name'] }}</td>
            <td>{{ $party['type'] }}</td>
        </tr>
        @endforeach
    </table>
    @endif

    @if($contract->clauses && count($contract->clauses) > 0)
    <div class="section-title">Legal Clauses</div>
    @foreach($contract->clauses as $clause)
        <div style="margin-bottom: 15px;">
            <strong>{{ $clause['number'] }} - {{ $clause['title'] }}</strong> (<em>{{ $clause['category'] }}</em>)
            <p style="margin-top: 5px;">{{ $clause['text'] }}</p>
        </div>
    @endforeach
    @endif

    <div class="footer">
        Confidential Contract Document. Exported from the Contract Management System.<br>
        This document was auto-generated.
    </div>
</body>
</html>
